"""Assembling a run: settings, event bus, renderer, clients, router, pauses.

The CLI declares flags; this decides what they mean. Kept out of `cli.py` so the same
assembly can be driven from a test with an injected transport and injected settings,
which is what makes a `--dry-run` regression test possible without a network.

Two of the choices here are the load-bearing ones:

**`router=None` is what "zero LLM calls" means.** A dry run is not a run with the model
calls skipped by convention — there is no router to call. Anything that tried would
raise rather than quietly spend.

**A declined pause still writes `charter.yaml`.** Declining at the charter pause is the
intended way to correct a taxonomy or a missing vocabulary, and that is only useful if
the file to edit is already on disk when the run stops.

**The renderer, the pause and the reviewer are injectable.** `--tui` supplies all three
and nothing else changes: a Textual app is a second subscriber to the same bus and a
second implementation of the same two protocols, not a second way to run the graph.
"""

from __future__ import annotations

import asyncio
import importlib.util
import shutil
from collections.abc import AsyncIterator, Callable
from contextlib import asynccontextmanager
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from okf_loremaster.curation import MAX_ROUNDS
from okf_loremaster.extraction_cache import ExtractionCache
from okf_loremaster.finalize import Finalize
from okf_loremaster.okf.layout import okf_bundle_path
from okf_loremaster.schemas import (
    DEFAULT_MAX_TOPICS,
    DEFAULT_TARGET_PAPERS,
    DEFAULT_TOPIC_PAPER_MAX,
    DEFAULT_TOPIC_PAPER_MIN,
    Charter,
)

if TYPE_CHECKING:  # imported lazily below; litellm and httpx are slow to import
    import httpx
    from rich.console import Console

    from okf_loremaster.config import Settings
    from okf_loremaster.emitters.vectors import Embedder
    from okf_loremaster.events import EventBus
    from okf_loremaster.graph.state import RunState
    from okf_loremaster.llm.router import Router
    from okf_loremaster.review import Reviewer
    from okf_loremaster.ui.pauses import Pause

__all__ = [
    "TRANSCRIPT_FILENAME",
    "PastRun",
    "RunInterrupted",
    "RunOptions",
    "build_run",
    "embedder",
    "find_run",
    "list_runs",
    "new_run_id",
    "require_textual",
    "run_directory",
]

CHARTER_FILENAME = "charter.yaml"

# The full-screen renderer's log pane, kept as plain text in the run folder. Named here
# rather than in `ui/tui.py` so the CLI can point at it without importing Textual, which
# is an optional extra.
TRANSCRIPT_FILENAME = "run.log"

# How many past runs `okf-loremaster runs` shows. A resumable run is one somebody
# remembers starting, so a long tail of them is history rather than a work queue.
DEFAULT_RUN_LIST = 10


class RunInterrupted(Exception):
    """A run stopped on purpose, part way. Carries the id needed to resume it.

    Distinct from a failure: nothing went wrong, and the checkpoint is intact. Defined
    here rather than in `ui.tui` so the CLI can catch it without importing textual.
    """

    def __init__(self, run_id: str) -> None:
        super().__init__(f"run {run_id} stopped before finishing")
        self.run_id = run_id


def new_run_id() -> str:
    """A sortable, unique run id. It is also the checkpoint thread id and the run
    directory name, so it has to be filesystem-safe and orderable."""
    return f"{datetime.now(UTC):%Y%m%d-%H%M%S}-{uuid4().hex[:4]}"


@dataclass(frozen=True, slots=True)
class PastRun:
    """One resumable run, as `okf-loremaster runs` reports it."""

    run_id: str
    started: datetime | None
    prompt: str
    reached: str
    finished: bool
    # Where the original run wrote, so resuming it without `-o` lands there again
    # instead of in a second folder named after the id. Empty for a run checkpointed
    # before this was recorded.
    directory: str = ""


def started_at(run_id: str) -> datetime | None:
    """The timestamp a run id encodes, or None if it does not encode one.

    Read back out of the id rather than stored anywhere, because `new_run_id` puts it
    there and a second copy is a second thing to disagree. Tolerant of an id that was
    typed by hand or generated by an older version: this feeds a listing, and a run with
    no date beside it is still a run somebody can resume.
    """
    try:
        return datetime.strptime(run_id[:15], "%Y%m%d-%H%M%S").replace(tzinfo=UTC)
    except ValueError:
        return None


async def list_runs(settings: Settings, limit: int = DEFAULT_RUN_LIST) -> list[PastRun]:
    """Recent runs in the checkpoint store, newest first.

    This exists because `--resume` takes a run id and there was nowhere to get one. The
    id is printed when a run stops, and it names the output folder only when `-o` was not
    given — so for anyone who passes `-o` and closes the terminal, a resumable run became
    unreachable and its checkpoint was just disk. The store knew the whole time.

    The prompt is carried alongside the id because the ids are timestamps, and a person
    picking between four of them from this morning is choosing by what they asked, not by
    the minute they asked it.
    """
    async with _store(settings) as saver:
        # Ordered by id rather than by any stored time, because the id begins with a
        # sortable timestamp and a lexical sort over it is the same order.
        cursor = await saver.conn.execute(
            "SELECT DISTINCT thread_id FROM checkpoints ORDER BY thread_id DESC LIMIT ?",
            (limit,),
        )
        thread_ids = [str(row[0]) for row in await cursor.fetchall()]
        return [await _read_run(saver, thread_id) for thread_id in thread_ids]


async def find_run(settings: Settings, run_id: str) -> PastRun | None:
    """One run from the checkpoint store, or None if that id is not in it.

    Used by `--resume` to recover the prompt, so that resuming needs only the id. The
    prompt is part of the checkpointed state, and asking a user to retype the sentence
    the store is already holding is asking them to get it wrong.
    """
    async with _store(settings) as saver:
        cursor = await saver.conn.execute(
            "SELECT 1 FROM checkpoints WHERE thread_id = ? LIMIT 1", (run_id,)
        )
        if await cursor.fetchone() is None:
            return None
        return await _read_run(saver, run_id)


@asynccontextmanager
async def _store(settings: Settings) -> AsyncIterator[Any]:
    """The checkpoint store, with its tables guaranteed to exist.

    The saver creates them on first write, so before any run has ever been built there
    is a database file with nothing in it — and asking it what runs there are answered
    `no such table: checkpoints`. The first thing a new user would plausibly type is not
    a good place for a traceback. `setup` is idempotent and is what the graph does too.
    """
    from okf_loremaster.graph.build import checkpointer

    async with checkpointer(settings) as saver:
        await saver.setup()
        yield saver


async def _read_run(saver: Any, run_id: str) -> PastRun:
    """Summarize one thread from its latest checkpoint."""
    config: Any = {"configurable": {"thread_id": run_id}}
    saved = await saver.aget_tuple(config)
    values = saved.checkpoint.get("channel_values", {}) if saved is not None else {}
    return PastRun(
        run_id=run_id,
        started=started_at(run_id),
        # Carried alongside the id because the ids are timestamps, and a person picking
        # between four of them from this morning is choosing by what they asked, not by
        # the minute they asked it.
        prompt=str(values.get("prompt") or ""),
        # What the run got through, named by the last node whose output is in the state.
        # Cheaper and steadier than reading LangGraph's own step bookkeeping, which is
        # about the graph rather than about the work.
        reached=_reached(values),
        finished=bool(values.get("validated")),
        directory=str(values.get("directory") or ""),
    )


# State keys in graph order, each the output of the node that produced it. Read from the
# end, the first one present is how far the run got.
_MILESTONES: tuple[tuple[str, str], ...] = (
    ("charter", "charter"),
    ("plan", "search"),
    ("pool", "rank"),
    ("verdicts", "screen"),
    ("topics", "curate"),
    ("texts", "fulltext"),
    ("extractions", "extract"),
    ("records", "reconcile"),
    ("bundle", "emit_okf"),
)


def _reached(values: dict[str, Any]) -> str:
    for key, node in reversed(_MILESTONES):
        if values.get(key):
            return node
    return "not started"


@dataclass(frozen=True, slots=True)
class RunOptions:
    """Everything the CLI decided, in one place."""

    prompt: str = ""
    charter_path: Path | None = None
    out: Path | None = None
    pool_size: int = 800
    screen_budget: int = 400
    target_papers: int = DEFAULT_TARGET_PAPERS
    topic_paper_min: int = DEFAULT_TOPIC_PAPER_MIN
    topic_paper_max: int = DEFAULT_TOPIC_PAPER_MAX
    max_topics: int = DEFAULT_MAX_TOPICS
    max_queries: int = 12
    max_rounds: int = MAX_ROUNDS
    # Stop at the charter and the retrieved pool and ask. Off by default: a run is
    # autonomous end to end unless someone asks to be in it. The two pauses still print
    # what they would have asked about, so an unattended run is not a silent one.
    interactive: bool = False
    # Ask for human sign-off before the bundle is written. Refused with `--dry-run` or
    # `--json` by the CLI: auto-signing would attribute `human:<id>` to someone who
    # never looked.
    review: bool = False
    # What the run keeps. `None` means nobody has said yet, so an attended run is asked
    # at the end and an unattended one takes `BOTH` — the answer that discards nothing.
    finalize: Finalize | None = None
    dry_run: bool = False
    resume: str | None = None
    # Full-screen Textual interface. Refused with `--json` by the CLI, and quietly
    # declined for `--dry-run` or a terminal that cannot drive it.
    tui: bool = False
    json_out: bool = False
    verbose: int = 0


def run_directory(
    options: RunOptions, settings: Settings, run_id: str, *, remembered: str = ""
) -> Path:
    """The folder holding everything this run produces — `okf/` and `vectors/`.

    One folder rather than two siblings so that moving the deliverable into a consumer
    is a single copy. Without `-o` the run id names it, which is unique and sortable but
    not memorable. With `-o` the name is the user's, resolved under the configured
    output directory — see `Settings.resolve_output`.

    `remembered` is where the run being resumed wrote the first time. It wins over the
    run id, because `-o` is a property of the run rather than of the invocation: a run
    named on Monday and resumed on Tuesday without retyping the name used to finish in
    a second folder called `20260804-111902-b537`, leaving the named one half-built and
    the finished bundle somewhere nobody looked for it. An explicit `-o` still wins over
    both, which is how a resumed run is deliberately written somewhere else.
    """
    if options.out is not None:
        return settings.resolve_output(options.out)
    if remembered:
        return Path(remembered)
    return settings.output_dir / run_id


# --- the build command ------------------------------------------------------


async def build_run(
    options: RunOptions,
    *,
    console: Console | None = None,
    settings: Settings | None = None,
    transport: httpx.AsyncBaseTransport | None = None,
    attach: Callable[[EventBus], asyncio.Task[None]] | None = None,
    pause: Pause | None = None,
    reviewer: Reviewer | None = None,
) -> tuple[RunState, Path]:
    """Run the whole graph, `charter` through `validate`, plus any re-query round it
    asks for. Returns the state and the run directory.

    Returns rather than raises on a declined pause: a run stopped after ranking has
    still produced a real query plan and a real pool, and the caller wants to report
    them.

    `attach`, `pause` and `reviewer` override the console surfaces. `attach` is handed
    the bus and returns a task that must end when the bus closes — the same contract
    `_start_renderer` satisfies, so the lifecycle below does not change shape.
    """
    from okf_loremaster.clients import build_clients
    from okf_loremaster.config import load_settings
    from okf_loremaster.events import EventBus
    from okf_loremaster.graph.build import run_build
    from okf_loremaster.graph.state import Deps

    resolved = settings if settings is not None else load_settings()
    # Checked before anything is built, so a missing model name fails in a sentence
    # rather than three nodes deep. A dry run needs none of it.
    if not options.dry_run:
        resolved.require_llm()

    charter = _load_charter(options.charter_path)
    prompt = options.prompt or (charter.prompt if charter is not None else "")
    past: PastRun | None = None
    if options.resume is not None:
        # Read back rather than retyped. On resume the prompt is not an input at all —
        # the graph replays from the checkpoint and never re-reads it — so a prompt
        # supplied here would only be the sentence the run is *labeled* with, and a
        # retyped one that differs from the original mislabels it.
        past = await find_run(resolved, options.resume)
        if past is None:
            raise ValueError(
                f"no run {options.resume} in the checkpoint store — "
                f"`okf-loremaster runs` lists the ones that are"
            )
        prompt = past.prompt or prompt
    if not prompt:
        raise ValueError(
            "no prompt: pass one as the argument to `build`, or `--resume <id>` to pick "
            "an unfinished run back up. `okf-loremaster runs` lists them."
        )

    run_id = options.resume or new_run_id()
    # Decided here, before the graph starts, and carried on `Deps`. The emit node must
    # not work it out for itself: a resumed run would then land somewhere else than the
    # run it resumed.
    directory = run_directory(
        options, resolved, run_id, remembered=past.directory if past is not None else ""
    )
    corpus = okf_bundle_path(directory)
    # Settled before the graph starts because the embedder has to be built or not built
    # up front, and an unattended run has nobody to ask later.
    finalize = options.finalize if options.finalize is not None else Finalize.BOTH
    bus = EventBus()
    task = attach(bus) if attach is not None else _start_renderer(bus, options, console)

    clients = build_clients(resolved, bus=bus, transport=transport)
    router = None if options.dry_run else _router(resolved, bus)
    deps = Deps(
        settings=resolved,
        bus=bus,
        clients=clients,
        router=router,
        bundle_dir=corpus,
        reviewer=reviewer if reviewer is not None else _reviewer(options, resolved, console),
        embedder=embedder(resolved) if finalize.builds_vectors else None,
        # Not on a dry run, which makes no calls and so has nothing to remember. Shared
        # across runs rather than kept under the run directory: the same paper read for
        # the same question is the same reading, and scoping it per run would mean a
        # rerun after a crash starts from nothing.
        extraction_cache=None if options.dry_run else ExtractionCache(
            resolved.cache_dir / "extractions"
        ),
        pool_size=options.pool_size,
        screen_budget=options.screen_budget,
        max_queries=options.max_queries,
        max_rounds=options.max_rounds,
        target_papers=options.target_papers,
        topic_paper_min=options.topic_paper_min,
        topic_paper_max=options.topic_paper_max,
        max_topics=options.max_topics,
    )

    try:
        state = await run_build(
            run_id=run_id,
            prompt=prompt,
            deps=deps,
            pause=pause if pause is not None else _pause(options, console),
            charter=charter,
            dry_run=options.dry_run,
            resume=options.resume is not None,
            directory=str(directory),
        )
    finally:
        await clients.aclose()
        bus.close()
        await task

    settled = state.get("charter")
    if settled is not None:
        # At the run root, not inside `okf/`. A run that stopped at a pause never
        # reached `emit_okf` and has no corpus to put it in, and this copy is the one a
        # person edits and reruns from. The emitter writes a second copy inside the
        # corpus so that moving `okf/` on its own still carries its terms with it.
        _write_charter(settled, directory / CHARTER_FILENAME)

    if state.get("bundle") and not options.dry_run:
        _settle_finalize(options.finalize, corpus, console=console)
    return state, directory


# --- what the run keeps ------------------------------------------------------


def _settle_finalize(chosen: Finalize | None, corpus: Path, *, console: Console | None) -> Finalize:
    """Ask what to keep, then make it so. Returns what was actually kept.

    Asked at the end rather than up front because it is a question about a thing that
    now exists: by this point both resources are on disk and their sizes can be shown.
    `--finalize` answers it in advance, which is the only way to skip the embedding pass
    entirely — an unattended run keeps both, because discarding work nobody asked to
    discard is the one outcome that cannot be undone without paying for the run again.
    """
    from okf_loremaster.okf.layout import vector_store_path

    store = vector_store_path(corpus)
    if chosen is None:
        chosen = _ask_finalize(corpus, store, console=console)

    if not chosen.builds_vectors and store.exists():
        shutil.rmtree(store)
    if not chosen.keeps_okf and corpus.exists():
        shutil.rmtree(corpus)
    return chosen


def _ask_finalize(corpus: Path, store: Path, *, console: Console | None) -> Finalize:
    """The end-of-run question, or `BOTH` when there is nobody to ask.

    A terminal that cannot prompt is not a terminal that should be guessed at, so every
    non-interactive path lands on the answer that deletes nothing.
    """
    import sys

    from rich.prompt import IntPrompt

    from okf_loremaster.finalize import PROMPT_ORDER
    from okf_loremaster.ui.plain import rich_enabled

    if not sys.stdin.isatty() or not rich_enabled():
        return Finalize.BOTH

    out = console if console is not None else _default_console()
    out.print()
    out.print("[bold]finalize this run as[/bold]")
    for number, option in enumerate(PROMPT_ORDER, start=1):
        where = corpus if option.keeps_okf else store
        size = _folder_size(corpus if option.keeps_okf else store)
        detail = f"{where.name}/" if option is not Finalize.BOTH else "both folders"
        out.print(f"  [cyan]{number}[/cyan]  {option.label}  [dim]{detail}  {size}[/dim]")

    answer = IntPrompt.ask(
        "keep", choices=[str(n) for n in range(1, len(PROMPT_ORDER) + 1)], default=3, console=out
    )
    picked = PROMPT_ORDER[answer - 1]
    if picked.keeps_okf:
        return picked

    # The corpus is what the run actually paid for, and the vector store is rebuilt from
    # it. Deleting it is the one answer worth asking twice about.
    from rich.prompt import Confirm

    if not Confirm.ask(
        f"[yellow]delete[/yellow] {corpus}? rebuilding it costs another full run",
        default=False,
        console=out,
    ):
        return Finalize.BOTH
    return picked


def _folder_size(path: Path) -> str:
    """Rough on-disk size, for a question that is really about what to throw away."""
    if not path.exists():
        return "not built"
    total = float(sum(item.stat().st_size for item in path.rglob("*") if item.is_file()))
    for unit in ("B", "KB", "MB", "GB"):
        if total < 1024 or unit == "GB":
            return f"{total:.0f} {unit}" if unit == "B" else f"{total:.1f} {unit}"
        total /= 1024.0
    return f"{total:.1f} GB"


def _default_console() -> Console:
    from rich.console import Console as RichConsole

    return RichConsole(stderr=True)


# --- shared -----------------------------------------------------------------


def _router(settings: Settings, bus: EventBus) -> Router:
    from okf_loremaster.llm.router import Router

    return Router(settings, bus)


def embedder(settings: Settings) -> Embedder:
    """The configured embedder, with the `[vectors]` extra checked first.

    The check is here rather than in the node because the node runs last: without it, a
    run that took an hour would reach the final step and only then discover that the
    thing it was asked to build cannot be built. Nothing is loaded — the import is a
    presence test, and the model itself downloads on first use.
    """
    from okf_loremaster.config import ConfigError
    from okf_loremaster.emitters.vectors import SentenceTransformerEmbedder

    for package in ("chromadb", "sentence_transformers"):
        if importlib.util.find_spec(package) is None:
            raise ConfigError(
                f"vector indexing needs {package}, which is not installed — "
                f"`pip install 'okf-loremaster[vectors]'`, or use --finalize okf"
            )
    return SentenceTransformerEmbedder(settings.embed_model, settings.embed_revision)


def require_textual() -> None:
    """Fail before the screen is cleared, not after.

    Same shape as the `[vectors]` check above and for the same reason: a missing extra
    should read as one sentence naming the fix, not as an ImportError from a UI module.
    """
    from okf_loremaster.config import ConfigError

    if importlib.util.find_spec("textual") is None:
        raise ConfigError(
            "the full-screen interface needs textual, which is not installed — "
            "`pip install 'okf-loremaster[tui]'`, or drop --tui"
        )


def _pause(options: RunOptions, console: Console | None) -> Pause:
    """Which confirmation surface to use.

    A run is autonomous unless `--interactive` asks for the pauses, so the default
    surface prints each decision and continues. `--json` is the one override: a
    machine-readable stream has nobody to ask, and printing tables into it would corrupt
    the thing the flag exists to produce.

    `--dry-run` is deliberately *not* an override. Interactivity used to be the default
    and a dry run opted out of it, because approving a run that costs nothing is noise.
    Now that asking has to be requested, honoring the request is the simpler rule and
    the one both renderers can share — and a dry run is exactly where rehearsing the
    decisions is cheap.
    """
    from okf_loremaster.ui.pauses import AutoApprove, ConsolePause

    if options.json_out:
        return AutoApprove()
    return ConsolePause(console, interactive=options.interactive)


def _reviewer(options: RunOptions, settings: Settings, console: Console | None) -> Reviewer | None:
    """The sign-off surface, or None when nobody asked for one.

    None is not a decline. It is the review node's signal that the question was never
    put, which is why a run without `--review` carries no warning about being unverified
    — an unsigned bundle is the normal case, not a shortfall.
    """
    if not options.review:
        return None
    from okf_loremaster.review import signer_id
    from okf_loremaster.ui.review import ConsoleReviewer

    return ConsoleReviewer(signer_id(settings), console=console)


def _start_renderer(
    bus: EventBus, options: RunOptions, console: Console | None
) -> asyncio.Task[None]:
    """Subscribe a renderer and start consuming. Await the task after closing the bus.

    The renderer subscribes in its constructor, so nothing emitted between here and the
    first `await` is lost; only the returned task needs keeping.
    """
    from okf_loremaster.ui.jsonl import JsonlRenderer
    from okf_loremaster.ui.plain import PlainRenderer

    renderer: JsonlRenderer | PlainRenderer
    if options.json_out:
        renderer = JsonlRenderer(bus)
    else:
        renderer = PlainRenderer(bus, console=console, verbose=options.verbose)
    return asyncio.create_task(renderer.run())


def _load_charter(path: Path | None) -> Charter | None:
    if path is None:
        return None
    if not path.exists():
        raise FileNotFoundError(f"no charter at {path}")
    return Charter.from_yaml(path.read_text(encoding="utf-8"))


def _write_charter(charter: Charter, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(charter.to_yaml(), encoding="utf-8")
